#!/usr/bin/env bash
set -e

RED=$'\033[31m'
GREEN=$'\033[32m'
TEXTRESET=$'\033[0m' # reset the foreground colour

# -failfast -timeout=5m
TESTFLAGS=(-race -cover "-coverprofile=cover.out" "${TESTFLAGS}")

if [ -n "${VERBOSE}" ]; then
    TESTFLAGS+=(-v)
elif [ -n "${VERBOSE_UNIT}" ]; then
    TESTFLAGS+=(-v)
fi

set +e

# shellcheck disable=SC2086
# shellcheck disable=SC2048
go test ${TESTFLAGS[*]} ./...
go tool cover -html=cover.out -o cover.html

CODE=$?
if [ ${CODE} != 0 ]; then
    echo "${RED}Tests failed [code ${CODE}].${TEXTRESET}"
    exit ${CODE}
else
    echo "${GREEN}Tests succeed.${TEXTRESET}"
fi